version: '3.9'

services:
  backend:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - UPLOAD_FOLDER=/app/uploads
      - OPENAI_KEY=${OPENAI_KEY}
      - REDIS_HOST=redis
    volumes:
      - ./backend-app/uploads:/app/uploads
    networks:
      - app-network
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge